### ISSUE TITLE
How to change the size of pip and leave it?

### ISSUE THREAD

**Issue by cangSDARM** [bostrot/flutter_android_pip#7]
as the title described

May add more activities for a helpful example.

**Comment by bostrot** [comment]
Android doesn't yet support that of my knowledge. Though this will be in the Android 11 release. The only thing you could do now is change the aspect ratio of the screen.

**Comment by cangSDARM** [comment]
Got it, then I close this issue.

**Comment by BrownieBits** [comment]
How would i change the aspect ratio? Basically when it is in PIP i just want a small square icon and when not, it would go to full size.
